In [1]:
import pandas as pd

In [4]:
def extract(filepath):
    df = pd.read_csv(filepath)
    return df

In [5]:
df = extract("sales_raw.csv")

In [7]:
df

   id         date  amount     category region
0   1   2024/01/15   250.0  Electronics  North
1   2  Jan 15 2024   180.5  ELECTRONICS  South
2   3   15-01-2024   320.0     clothing   East
3   4   2024/01/16     NaN  Electronics  North
4   5   16-01-2024   -50.0     Clothing   West
5   6  Jan 17 2024   410.0     CLOTHING  North
6   7   2024/01/17    90.0         food  South
7   8   17-01-2024   130.0         FOOD   East
8   9  Jan 18 2024     NaN         food   West
9  10   2024/01/18   200.0  Electronics  South

In [8]:
df = df.dropna(subset=["amount"])
df

   id         date  amount     category region
0   1   2024/01/15   250.0  Electronics  North
1   2  Jan 15 2024   180.5  ELECTRONICS  South
2   3   15-01-2024   320.0     clothing   East
4   5   16-01-2024   -50.0     Clothing   West
5   6  Jan 17 2024   410.0     CLOTHING  North
6   7   2024/01/17    90.0         food  South
7   8   17-01-2024   130.0         FOOD   East
9  10   2024/01/18   200.0  Electronics  South

In [9]:
df = df[df['amount']>0]

   id         date  amount     category region
0   1   2024/01/15   250.0  Electronics  North
1   2  Jan 15 2024   180.5  ELECTRONICS  South
2   3   15-01-2024   320.0     clothing   East
5   6  Jan 17 2024   410.0     CLOTHING  North
6   7   2024/01/17    90.0         food  South
7   8   17-01-2024   130.0         FOOD   East
9  10   2024/01/18   200.0  Electronics  South

In [16]:
df['date'] = pd.to_datetime(df['date'], format = 'mixed', dayfirst = True)

In [17]:
df

   id       date  amount     category region
0   1 2024-01-15   250.0  Electronics  North
1   2 2024-01-15   180.5  ELECTRONICS  South
2   3 2024-01-15   320.0     clothing   East
5   6 2024-01-17   410.0     CLOTHING  North
6   7 2024-01-17    90.0         food  South
7   8 2024-01-17   130.0         FOOD   East
9  10 2024-01-18   200.0  Electronics  South

In [18]:
df['category'] = df['category'].str.title()

In [19]:
df

   id       date  amount     category region
0   1 2024-01-15   250.0  Electronics  North
1   2 2024-01-15   180.5  Electronics  South
2   3 2024-01-15   320.0     Clothing   East
5   6 2024-01-17   410.0     Clothing  North
6   7 2024-01-17    90.0         Food  South
7   8 2024-01-17   130.0         Food   East
9  10 2024-01-18   200.0  Electronics  South

In [20]:
print("Categories:", df["category"].unique())

Categories: <ArrowStringArray>
['Electronics', 'Clothing', 'Food']
Length: 3, dtype: str

In [21]:
df['revenue_after_tax'] = df['amount'] * 0.9

In [22]:
df

   id       date  amount     category region  revenue_after_tax
0   1 2024-01-15   250.0  Electronics  North             225.00
1   2 2024-01-15   180.5  Electronics  South             162.45
2   3 2024-01-15   320.0     Clothing   East             288.00
5   6 2024-01-17   410.0     Clothing  North             369.00
6   7 2024-01-17    90.0         Food  South              81.00
7   8 2024-01-17   130.0         Food   East             117.00
9  10 2024-01-18   200.0  Electronics  South             180.00