In [1]:
import pandas as pd

In [4]:
def extract(filepath):
    df = pd.read_csv(filepath)
    return df

In [29]:
df = extract("sales_raw.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'sales_raw.csv'

In [ ]:
df

In [30]:
df = df.dropna(subset=["amount"])
df

   id       date  amount     category region  revenue_after_tax
0   1 2024-01-15   250.0  Electronics  North             225.00
1   2 2024-01-15   180.5  Electronics  South             162.45
2   3 2024-01-15   320.0     Clothing   East             288.00
5   6 2024-01-17   410.0     Clothing  North             369.00
6   7 2024-01-17    90.0         Food  South              81.00
7   8 2024-01-17   130.0         Food   East             117.00
9  10 2024-01-18   200.0  Electronics  South             180.00

In [31]:
df = df[df['amount']>0]

In [32]:
df['date'] = pd.to_datetime(df['date'], format = 'mixed', dayfirst = True)

In [33]:
df

   id       date  amount     category region  revenue_after_tax
0   1 2024-01-15   250.0  Electronics  North             225.00
1   2 2024-01-15   180.5  Electronics  South             162.45
2   3 2024-01-15   320.0     Clothing   East             288.00
5   6 2024-01-17   410.0     Clothing  North             369.00
6   7 2024-01-17    90.0         Food  South              81.00
7   8 2024-01-17   130.0         Food   East             117.00
9  10 2024-01-18   200.0  Electronics  South             180.00

In [34]:
df['category'] = df['category'].str.title()

In [35]:
df

   id       date  amount     category region  revenue_after_tax
0   1 2024-01-15   250.0  Electronics  North             225.00
1   2 2024-01-15   180.5  Electronics  South             162.45
2   3 2024-01-15   320.0     Clothing   East             288.00
5   6 2024-01-17   410.0     Clothing  North             369.00
6   7 2024-01-17    90.0         Food  South              81.00
7   8 2024-01-17   130.0         Food   East             117.00
9  10 2024-01-18   200.0  Electronics  South             180.00

In [36]:
print("Categories:", df["category"].unique())

Categories: <ArrowStringArray>
['Electronics', 'Clothing', 'Food']
Length: 3, dtype: str

In [37]:
df['revenue_after_tax'] = df['amount'] * 0.9

In [38]:
df

   id       date  amount     category region  revenue_after_tax
0   1 2024-01-15   250.0  Electronics  North             225.00
1   2 2024-01-15   180.5  Electronics  South             162.45
2   3 2024-01-15   320.0     Clothing   East             288.00
5   6 2024-01-17   410.0     Clothing  North             369.00
6   7 2024-01-17    90.0         Food  South              81.00
7   8 2024-01-17   130.0         Food   East             117.00
9  10 2024-01-18   200.0  Electronics  South             180.00

In [45]:
summary = df.groupby(['category', 'region'])['revenue_after_tax'].sum()
summary

category     region
Clothing     East      288.00
             North     369.00
Electronics  North     225.00
             South     342.45
Food         East      117.00
             South      81.00
Name: revenue_after_tax, dtype: float64

In [44]:
df

   id       date  amount     category region  revenue_after_tax
0   1 2024-01-15   250.0  Electronics  North             225.00
1   2 2024-01-15   180.5  Electronics  South             162.45
2   3 2024-01-15   320.0     Clothing   East             288.00
5   6 2024-01-17   410.0     Clothing  North             369.00
6   7 2024-01-17    90.0         Food  South              81.00
7   8 2024-01-17   130.0         Food   East             117.00
9  10 2024-01-18   200.0  Electronics  South             180.00